env:
  node: true,
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {
  "no-console": "off",
  "import/extensions": 0,
  "import/no-extraneous-dependencies": ["error", {"devDependencies": true}]
}
